# Generated by Django 5.2.3 on 2025-07-02 12:27

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(upload_to='receipts/')
        ),
    ]
